### ISSUE TITLE
Make data dynamic

### ISSUE THREAD

**Issue by piyushchauhan** [piyushchauhan/TEDxIITPatna#1]
Make data like contacts, names, etc. load from JSON file

**Comment by VatsalSin** [comment]
The amount of data is quite less to have a separate backend for it.

**Comment by VatsalSin** [comment]
And for the form Freshers are using Google forms I think that wil be enough

**Comment by piyushchauhan** [comment]
Load data from JSON doesn't require backend. Does it?

**Comment by VatsalSin** [comment]
If not done through backend. Then what's the point. We will always change json on server the same can be done to html

**Comment by piyushchauhan** [comment]
At least data, JSON is more structured than HTML.
